services:
  app:
    image: 'docker-card-cost-api:latest'
    build:
      context: .
    container_name: card-cost-api
    depends_on:
      - db
      - redis
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/card_cost_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: 'mysql:lts'
    container_name: card-costs-db
    environment:
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_DATABASE: card_cost_db

  redis:
    image: 'redis:latest'
    container_name: card-costs-redis-cache