spring:
  application:
    name: Card Cost API
  cache:
    redis:
      time-to-live: 10m
  data:
    redis:
      host: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

bintable:
  api-key: "<Your BINTable API key here}>"